
import { Ingredient, PotBase } from './types';

export const INGREDIENTS: Ingredient[] = [
  // Proteins
  {
    id: 'p1',
    name: 'ingredients.chicken_breast',
    category: 'protein',
    pPer100g: 23,
    fPer100g: 1.5,
    cPer100g: 0,
    kcalPer100g: 108,
    effect: 'effects.p1',
    photo: require('./assets/food_photos/むね肉.jpg'),
    photoSmall: require('./assets/food_photos/むね肉_sm.jpg'),
    unitWeight: 300,
    unitName: 'units.slice'
  },
  {
    id: 'p2',
    name: 'ingredients.pork_loin',
    category: 'protein',
    pPer100g: 19,
    fPer100g: 14,
    cPer100g: 0,
    kcalPer100g: 230,
    effect: 'effects.p2',
    photo: require('./assets/food_photos/豚ロース.jpg'),
    photoSmall: require('./assets/food_photos/豚ロース_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.pack'
  },
  {
    id: 'p8',
    name: 'ingredients.beef_round',
    category: 'protein',
    pPer100g: 21,
    fPer100g: 8,
    cPer100g: 0,
    kcalPer100g: 171,
    effect: 'effects.p8',
    photo: require('./assets/food_photos/牛ロース.jpg'),
    photoSmall: require('./assets/food_photos/牛ロース_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.pack'
  },
  {
    id: 'p9',
    name: 'ingredients.chicken_liver',
    category: 'protein',
    pPer100g: 18,
    fPer100g: 4,
    cPer100g: 1,
    kcalPer100g: 111,
    effect: 'effects.p9',
    photo: require('./assets/food_photos/chicken_liver.jpg'),
    photoSmall: require('./assets/food_photos/chicken_liver_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.pack'
  },
  {
    id: 'p3',
    name: 'ingredients.cod',
    category: 'protein',
    pPer100g: 17,
    fPer100g: 0.2,
    cPer100g: 0,
    kcalPer100g: 77,
    effect: 'effects.p3',
    photo: require('./assets/food_photos/たら.jpg'),
    photoSmall: require('./assets/food_photos/たら_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.fillet'
  },
  {
    id: 'p10',
    name: 'ingredients.salmon',
    category: 'protein',
    pPer100g: 20,
    fPer100g: 13,
    cPer100g: 0,
    kcalPer100g: 206,
    effect: 'effects.p10',
    photo: require('./assets/food_photos/サーモン.jpg'),
    photoSmall: require('./assets/food_photos/サーモン_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.fillet'
  },
  {
    id: 'p4',
    name: 'ingredients.firm_tofu',
    category: 'protein',
    pPer100g: 7,
    fPer100g: 3,
    cPer100g: 2,
    kcalPer100g: 60,
    effect: 'effects.p4',
    photo: require('./assets/food_photos/木綿豆腐.jpg'),
    photoSmall: require('./assets/food_photos/木綿豆腐_sm.jpg'),
    unitWeight: 400,
    unitName: 'units.block'
  },
  {
    id: 'p6',
    name: 'ingredients.canned_mackerel',
    category: 'protein',
    pPer100g: 20,
    fPer100g: 10,
    cPer100g: 0,
    kcalPer100g: 190,
    effect: 'effects.p6',
    photo: require('./assets/food_photos/さば水煮缶.jpg'),
    photoSmall: require('./assets/food_photos/さば水煮缶_sm.jpg'),
    unitWeight: 190,
    unitName: 'units.can'
  },
  {
    id: 'p7',
    name: 'ingredients.egg',
    category: 'protein',
    pPer100g: 12,
    fPer100g: 10,
    cPer100g: 1,
    kcalPer100g: 151,
    effect: 'effects.p7',
    photo: require('./assets/food_photos/たまご.jpg'),
    photoSmall: require('./assets/food_photos/たまご_sm.jpg'),
    unitWeight: 70,
    unitName: 'units.piece'
  },
  // Veggies
  {
    id: 'v1',
    name: 'ingredients.broccoli',
    category: 'veg',
    pPer100g: 4,
    fPer100g: 0.5,
    cPer100g: 5,
    kcalPer100g: 33,
    effect: 'effects.v1',
    photo: require('./assets/food_photos/ブロッコリー.jpg'),
    photoSmall: require('./assets/food_photos/ブロッコリー_sm.jpg'),
    unitWeight: 250,
    unitName: 'units.piece'
  },
  {
    id: 'v3',
    name: 'ingredients.shimeji',
    category: 'veg',
    pPer100g: 2,
    fPer100g: 0.3,
    cPer100g: 4,
    kcalPer100g: 18,
    effect: 'effects.v3',
    photo: require('./assets/food_photos/しめじ.jpg'),
    photoSmall: require('./assets/food_photos/しめじ_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.pack'
  },
  {
    id: 'v4',
    name: 'ingredients.komatsuna',
    category: 'veg',
    pPer100g: 2.8,
    fPer100g: 0.4,
    cPer100g: 3.5,
    kcalPer100g: 14,
    effect: 'effects.v4',
    photo: require('./assets/food_photos/小松菜.jpg'),
    photoSmall: require('./assets/food_photos/小松菜_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.bag'
  },
  {
    id: 'v5',
    name: 'ingredients.onion',
    category: 'veg',
    pPer100g: 1,
    fPer100g: 0.1,
    cPer100g: 9,
    kcalPer100g: 37,
    effect: 'effects.v5',
    photo: require('./assets/food_photos/玉ねぎ.jpg'),
    photoSmall: require('./assets/food_photos/玉ねぎ_sm.jpg'),
    unitWeight: 250,
    unitName: 'units.piece'
  },
  {
    id: 'v6',
    name: 'ingredients.daikon',
    category: 'veg',
    pPer100g: 0.5,
    fPer100g: 0.1,
    cPer100g: 4,
    kcalPer100g: 18,
    effect: 'effects.v6',
    photo: require('./assets/food_photos/大根.jpg'),
    photoSmall: require('./assets/food_photos/大根_sm.jpg'),
    unitWeight: 300,
    unitName: 'units.third_stick'
  },
  {
    id: 'v7',
    name: 'ingredients.carrot',
    category: 'veg',
    pPer100g: 0.7,
    fPer100g: 0.2,
    cPer100g: 7,
    kcalPer100g: 37,
    effect: 'effects.v7',
    photo: require('./assets/food_photos/にんじん.jpg'),
    photoSmall: require('./assets/food_photos/にんじん_sm.jpg'),
    unitWeight: 150,
    unitName: 'units.stick'
  },
  {
    id: 'v8',
    name: 'ingredients.spinach',
    category: 'veg',
    pPer100g: 2.2,
    fPer100g: 0.4,
    cPer100g: 3.1,
    kcalPer100g: 20,
    effect: 'effects.v8',
    photo: require('./assets/food_photos/ほうれん草.jpg'),
    photoSmall: require('./assets/food_photos/ほうれん草_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.bag'
  },
  {
    id: 'v9',
    name: 'ingredients.maitake',
    category: 'veg',
    pPer100g: 2,
    fPer100g: 0.3,
    cPer100g: 5,
    kcalPer100g: 22,
    effect: 'effects.v9',
    photo: require('./assets/food_photos/舞茸.jpg'),
    photoSmall: require('./assets/food_photos/舞茸_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.pack'
  },
  {
    id: 'v10',
    name: 'ingredients.enoki',
    category: 'veg',
    pPer100g: 2.7,
    fPer100g: 0.2,
    cPer100g: 7,
    kcalPer100g: 22,
    effect: 'effects.v10',
    photo: require('./assets/food_photos/えのき.jpg'),
    photoSmall: require('./assets/food_photos/えのき_sm.jpg'),
    unitWeight: 150,
    unitName: 'units.bag'
  },
  {
    id: 'v11',
    name: 'ingredients.asparagus',
    category: 'veg',
    pPer100g: 2.6,
    fPer100g: 0.2,
    cPer100g: 3.9,
    kcalPer100g: 21,
    effect: 'effects.v11',
    photo: require('./assets/food_photos/アスパラガス.jpg'),
    photoSmall: require('./assets/food_photos/アスパラガス_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.bunch'
  },
  {
    id: 'v12',
    name: 'ingredients.tomato',
    category: 'veg',
    pPer100g: 0.7,
    fPer100g: 0.1,
    cPer100g: 3.9,
    kcalPer100g: 18,
    effect: 'effects.v12',
    photo: require('./assets/food_photos/トマト.jpg'),
    photoSmall: require('./assets/food_photos/トマト_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.piece'
  },
  {
    id: 'v13',
    name: 'ingredients.paprika',
    category: 'veg',
    pPer100g: 1,
    fPer100g: 0.2,
    cPer100g: 6,
    kcalPer100g: 31,
    effect: 'effects.v13',
    photo: require('./assets/food_photos/パプリカ.jpg'),
    photoSmall: require('./assets/food_photos/パプリカ_sm.jpg'),
    unitWeight: 150,
    unitName: 'units.piece'
  },
  // Carbs
  {
    id: 'c2',
    name: 'ingredients.udon',
    category: 'carb',
    pPer100g: 2.6,
    fPer100g: 0.4,
    cPer100g: 21,
    kcalPer100g: 105,
    effect: 'effects.c2',
    photo: require('./assets/food_photos/うどん.jpg'),
    photoSmall: require('./assets/food_photos/うどん_sm.jpg'),
    unitWeight: 250,
    unitName: 'units.ball'
  },
  {
    id: 'c3',
    name: 'ingredients.white_rice',
    category: 'carb',
    pPer100g: 2.5,
    fPer100g: 0.3,
    cPer100g: 37,
    kcalPer100g: 168,
    effect: 'effects.c3',
    photo: require('./assets/food_photos/白ごはん.jpg'),
    photoSmall: require('./assets/food_photos/白ごはん_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.cup'
  },
  {
    id: 'c4',
    name: 'ingredients.soba',
    category: 'carb',
    pPer100g: 4.8,
    fPer100g: 0.6,
    cPer100g: 26,
    kcalPer100g: 132,
    effect: 'effects.c4',
    photo: require('./assets/food_photos/そば.jpg'),
    photoSmall: require('./assets/food_photos/そば_sm.jpg'),
    unitWeight: 260,
    unitName: 'units.bag'
  },
  {
    id: 'c5',
    name: 'ingredients.sweet_potato',
    category: 'carb',
    pPer100g: 1.2,
    fPer100g: 0.2,
    cPer100g: 31,
    kcalPer100g: 132,
    effect: 'effects.c5',
    photo: require('./assets/food_photos/さつまいも.jpg'),
    photoSmall: require('./assets/food_photos/さつまいも_sm.jpg'),
    unitWeight: 300,
    unitName: 'units.stick'
  },
  {
    id: 'c6',
    name: 'ingredients.whole_wheat_bread',
    category: 'carb',
    pPer100g: 7.9,
    fPer100g: 5.7,
    cPer100g: 45.5,
    kcalPer100g: 251,
    effect: 'effects.c6',
    photo: require('./assets/food_photos/全粒粉パン.jpg'),
    photoSmall: require('./assets/food_photos/全粒粉パン_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.slice'
  },
  {
    id: 'c7',
    name: 'ingredients.pasta',
    category: 'carb',
    pPer100g: 12,
    fPer100g: 2,
    cPer100g: 72,
    kcalPer100g: 371,
    effect: 'effects.c7',
    photo: require('./assets/food_photos/パスタ.jpg'),
    photoSmall: require('./assets/food_photos/パスタ_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.bunch'
  }
];

export const POT_BASES: { id: PotBase; name: string; description: string; color: string }[] = [
  { id: 'yose', name: 'bases.names.yose', description: 'bases.desc.yose', color: '#fef3c7' },
  { id: 'miso', name: 'bases.names.miso', description: 'bases.desc.miso', color: '#ffedd5' },
  { id: 'kimchi', name: 'bases.names.kimchi', description: 'bases.desc.kimchi', color: '#fee2e2' },
];
