
import { Ingredient, PotBase } from './types';

export const INGREDIENTS: Ingredient[] = [
  // Proteins
  {
    id: 'p1',
    name: 'ingredients.chicken_breast',
    category: 'protein',
    pPer100g: 23,
    fPer100g: 1.5,
    cPer100g: 0,
    kcalPer100g: 108,
    effect: 'effects.p1',
    photo: require('./assets/food_photos/food_001.jpg'),
    photoSmall: require('./assets/food_photos/food_001_sm.jpg'),
    unitWeight: 300,
    unitName: 'units.slice'
  },
  {
    id: 'p2',
    name: 'ingredients.pork_loin',
    category: 'protein',
    pPer100g: 19,
    fPer100g: 14,
    cPer100g: 0,
    kcalPer100g: 230,
    effect: 'effects.p2',
    photo: require('./assets/food_photos/food_002.jpg'),
    photoSmall: require('./assets/food_photos/food_002_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.pack'
  },
  {
    id: 'p8',
    name: 'ingredients.beef_round',
    category: 'protein',
    pPer100g: 21,
    fPer100g: 8,
    cPer100g: 0,
    kcalPer100g: 171,
    effect: 'effects.p8',
    photo: require('./assets/food_photos/food_003.jpg'),
    photoSmall: require('./assets/food_photos/food_003_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.pack'
  },
  {
    id: 'p9',
    name: 'ingredients.chicken_liver',
    category: 'protein',
    pPer100g: 18,
    fPer100g: 4,
    cPer100g: 1,
    kcalPer100g: 111,
    effect: 'effects.p9',
    photo: require('./assets/food_photos/food_004.jpg'),
    photoSmall: require('./assets/food_photos/food_004_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.pack'
  },
  {
    id: 'p3',
    name: 'ingredients.cod',
    category: 'protein',
    pPer100g: 17,
    fPer100g: 0.2,
    cPer100g: 0,
    kcalPer100g: 77,
    effect: 'effects.p3',
    photo: require('./assets/food_photos/food_005.jpg'),
    photoSmall: require('./assets/food_photos/food_005_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.fillet'
  },
  {
    id: 'p10',
    name: 'ingredients.salmon',
    category: 'protein',
    pPer100g: 20,
    fPer100g: 13,
    cPer100g: 0,
    kcalPer100g: 206,
    effect: 'effects.p10',
    photo: require('./assets/food_photos/food_006.jpg'),
    photoSmall: require('./assets/food_photos/food_006_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.fillet'
  },
  {
    id: 'p4',
    name: 'ingredients.firm_tofu',
    category: 'protein',
    pPer100g: 7,
    fPer100g: 3,
    cPer100g: 2,
    kcalPer100g: 60,
    effect: 'effects.p4',
    photo: require('./assets/food_photos/food_007.jpg'),
    photoSmall: require('./assets/food_photos/food_007_sm.jpg'),
    unitWeight: 400,
    unitName: 'units.block'
  },
  {
    id: 'p6',
    name: 'ingredients.canned_mackerel',
    category: 'protein',
    pPer100g: 20,
    fPer100g: 10,
    cPer100g: 0,
    kcalPer100g: 190,
    effect: 'effects.p6',
    photo: require('./assets/food_photos/food_008.jpg'),
    photoSmall: require('./assets/food_photos/food_008_sm.jpg'),
    unitWeight: 190,
    unitName: 'units.can'
  },
  {
    id: 'p7',
    name: 'ingredients.egg',
    category: 'protein',
    pPer100g: 12,
    fPer100g: 10,
    cPer100g: 1,
    kcalPer100g: 151,
    effect: 'effects.p7',
    photo: require('./assets/food_photos/food_009.jpg'),
    photoSmall: require('./assets/food_photos/food_009_sm.jpg'),
    unitWeight: 70,
    unitName: 'units.piece'
  },
  // Veggies
  {
    id: 'v1',
    name: 'ingredients.broccoli',
    category: 'veg',
    pPer100g: 4,
    fPer100g: 0.5,
    cPer100g: 5,
    kcalPer100g: 33,
    effect: 'effects.v1',
    photo: require('./assets/food_photos/food_010.jpg'),
    photoSmall: require('./assets/food_photos/food_010_sm.jpg'),
    unitWeight: 250,
    unitName: 'units.piece'
  },
  {
    id: 'v3',
    name: 'ingredients.shimeji',
    category: 'veg',
    pPer100g: 2,
    fPer100g: 0.3,
    cPer100g: 4,
    kcalPer100g: 18,
    effect: 'effects.v3',
    photo: require('./assets/food_photos/food_011.jpg'),
    photoSmall: require('./assets/food_photos/food_011_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.pack'
  },
  {
    id: 'v4',
    name: 'ingredients.komatsuna',
    category: 'veg',
    pPer100g: 2.8,
    fPer100g: 0.4,
    cPer100g: 3.5,
    kcalPer100g: 14,
    effect: 'effects.v4',
    photo: require('./assets/food_photos/food_012.jpg'),
    photoSmall: require('./assets/food_photos/food_012_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.bag'
  },
  {
    id: 'v5',
    name: 'ingredients.onion',
    category: 'veg',
    pPer100g: 1,
    fPer100g: 0.1,
    cPer100g: 9,
    kcalPer100g: 37,
    effect: 'effects.v5',
    photo: require('./assets/food_photos/food_013.jpg'),
    photoSmall: require('./assets/food_photos/food_013_sm.jpg'),
    unitWeight: 250,
    unitName: 'units.piece'
  },
  {
    id: 'v6',
    name: 'ingredients.daikon',
    category: 'veg',
    pPer100g: 0.5,
    fPer100g: 0.1,
    cPer100g: 4,
    kcalPer100g: 18,
    effect: 'effects.v6',
    photo: require('./assets/food_photos/food_014.jpg'),
    photoSmall: require('./assets/food_photos/food_014_sm.jpg'),
    unitWeight: 300,
    unitName: 'units.third_stick'
  },
  {
    id: 'v7',
    name: 'ingredients.carrot',
    category: 'veg',
    pPer100g: 0.7,
    fPer100g: 0.2,
    cPer100g: 7,
    kcalPer100g: 37,
    effect: 'effects.v7',
    photo: require('./assets/food_photos/food_015.jpg'),
    photoSmall: require('./assets/food_photos/food_015_sm.jpg'),
    unitWeight: 150,
    unitName: 'units.stick'
  },
  {
    id: 'v8',
    name: 'ingredients.spinach',
    category: 'veg',
    pPer100g: 2.2,
    fPer100g: 0.4,
    cPer100g: 3.1,
    kcalPer100g: 20,
    effect: 'effects.v8',
    photo: require('./assets/food_photos/food_016.jpg'),
    photoSmall: require('./assets/food_photos/food_016_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.bag'
  },
  {
    id: 'v9',
    name: 'ingredients.maitake',
    category: 'veg',
    pPer100g: 2,
    fPer100g: 0.3,
    cPer100g: 5,
    kcalPer100g: 22,
    effect: 'effects.v9',
    photo: require('./assets/food_photos/food_017.jpg'),
    photoSmall: require('./assets/food_photos/food_017_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.pack'
  },
  {
    id: 'v10',
    name: 'ingredients.enoki',
    category: 'veg',
    pPer100g: 2.7,
    fPer100g: 0.2,
    cPer100g: 7,
    kcalPer100g: 22,
    effect: 'effects.v10',
    photo: require('./assets/food_photos/food_018.jpg'),
    photoSmall: require('./assets/food_photos/food_018_sm.jpg'),
    unitWeight: 150,
    unitName: 'units.bag'
  },
  {
    id: 'v11',
    name: 'ingredients.asparagus',
    category: 'veg',
    pPer100g: 2.6,
    fPer100g: 0.2,
    cPer100g: 3.9,
    kcalPer100g: 21,
    effect: 'effects.v11',
    photo: require('./assets/food_photos/food_019.jpg'),
    photoSmall: require('./assets/food_photos/food_019_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.bunch'
  },
  {
    id: 'v12',
    name: 'ingredients.tomato',
    category: 'veg',
    pPer100g: 0.7,
    fPer100g: 0.1,
    cPer100g: 3.9,
    kcalPer100g: 18,
    effect: 'effects.v12',
    photo: require('./assets/food_photos/food_020.jpg'),
    photoSmall: require('./assets/food_photos/food_020_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.piece'
  },
  {
    id: 'v13',
    name: 'ingredients.paprika',
    category: 'veg',
    pPer100g: 1,
    fPer100g: 0.2,
    cPer100g: 6,
    kcalPer100g: 31,
    effect: 'effects.v13',
    photo: require('./assets/food_photos/food_021.jpg'),
    photoSmall: require('./assets/food_photos/food_021_sm.jpg'),
    unitWeight: 150,
    unitName: 'units.piece'
  },
  // Carbs
  {
    id: 'c2',
    name: 'ingredients.udon',
    category: 'carb',
    pPer100g: 2.6,
    fPer100g: 0.4,
    cPer100g: 21,
    kcalPer100g: 105,
    effect: 'effects.c2',
    photo: require('./assets/food_photos/food_022.jpg'),
    photoSmall: require('./assets/food_photos/food_022_sm.jpg'),
    unitWeight: 250,
    unitName: 'units.ball'
  },
  {
    id: 'c3',
    name: 'ingredients.white_rice',
    category: 'carb',
    pPer100g: 2.5,
    fPer100g: 0.3,
    cPer100g: 37,
    kcalPer100g: 168,
    effect: 'effects.c3',
    photo: require('./assets/food_photos/food_023.jpg'),
    photoSmall: require('./assets/food_photos/food_023_sm.jpg'),
    unitWeight: 200,
    unitName: 'units.cup'
  },
  {
    id: 'c4',
    name: 'ingredients.soba',
    category: 'carb',
    pPer100g: 4.8,
    fPer100g: 0.6,
    cPer100g: 26,
    kcalPer100g: 132,
    effect: 'effects.c4',
    photo: require('./assets/food_photos/food_024.jpg'),
    photoSmall: require('./assets/food_photos/food_024_sm.jpg'),
    unitWeight: 260,
    unitName: 'units.bag'
  },
  {
    id: 'c5',
    name: 'ingredients.sweet_potato',
    category: 'carb',
    pPer100g: 1.2,
    fPer100g: 0.2,
    cPer100g: 31,
    kcalPer100g: 132,
    effect: 'effects.c5',
    photo: require('./assets/food_photos/food_025.jpg'),
    photoSmall: require('./assets/food_photos/food_025_sm.jpg'),
    unitWeight: 300,
    unitName: 'units.stick'
  },
  {
    id: 'c6',
    name: 'ingredients.whole_wheat_bread',
    category: 'carb',
    pPer100g: 7.9,
    fPer100g: 5.7,
    cPer100g: 45.5,
    kcalPer100g: 251,
    effect: 'effects.c6',
    photo: require('./assets/food_photos/food_026.jpg'),
    photoSmall: require('./assets/food_photos/food_026_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.slice'
  },
  {
    id: 'c7',
    name: 'ingredients.pasta',
    category: 'carb',
    pPer100g: 12,
    fPer100g: 2,
    cPer100g: 72,
    kcalPer100g: 371,
    effect: 'effects.c7',
    photo: require('./assets/food_photos/food_027.jpg'),
    photoSmall: require('./assets/food_photos/food_027_sm.jpg'),
    unitWeight: 100,
    unitName: 'units.bunch'
  }
];

export const POT_BASES: { id: PotBase; name: string; description: string; color: string }[] = [
  { id: 'yose', name: 'bases.names.yose', description: 'bases.desc.yose', color: '#fef3c7' },
  { id: 'miso', name: 'bases.names.miso', description: 'bases.desc.miso', color: '#ffedd5' },
  { id: 'kimchi', name: 'bases.names.kimchi', description: 'bases.desc.kimchi', color: '#fee2e2' },
];
