import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#ffffff' },
  autoVegMiniToast: {
    position: 'absolute',
    top: 12,
    alignSelf: 'center',
    zIndex: 40,
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  autoVegMiniToastText: { color: '#ffffff', fontSize: 12, fontWeight: '800' },
  autoVegHudWrap: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 50,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  autoVegHudCard: {
    maxWidth: 440,
    width: '100%',
    borderRadius: 16,
    backgroundColor: 'rgba(17, 24, 39, 0.95)',
    borderWidth: 1,
    borderColor: '#f59e0b',
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  autoVegHudText: {
    color: '#ffffff',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  synergyIntroHudWrap: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 55,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
  },
  synergyIntroHudCard: {
    maxWidth: 460,
    width: '100%',
    borderRadius: 18,
    backgroundColor: 'rgba(17, 24, 39, 0.96)',
    borderWidth: 1,
    borderColor: '#f59e0b',
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.25,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  synergyIntroHudTitle: {
    color: '#facc15',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
  },
  synergyIntroHudSubtitle: {
    color: '#fde68a',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 8,
    textAlign: 'center',
  },
  synergyIntroHudReason: {
    color: '#f8fafc',
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  synergyCard: {
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
    borderWidth: 1,
  },
  synergyCardRecommended: {
    backgroundColor: '#1A1A1A',
    borderColor: '#f59e0b',
  },
  synergyCardCustom: {
    backgroundColor: '#374151',
    borderColor: '#9ca3af',
  },
  synergyCardLabel: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  synergyCardLabelRecommended: {
    color: '#fbbf24',
  },
  synergyCardLabelCustom: {
    color: '#ffffff',
  },
  synergyCardMessage: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  synergyCardSubMessage: {
    marginTop: 6,
    color: '#d1d5db',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  synergyCardSubMessageRecommended: {
    marginTop: 0,
    marginBottom: 6,
    color: '#fde68a',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  synergyResetButton: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: '#111827',
    borderColor: '#9ca3af',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  synergyResetButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  webRoot: { backgroundColor: '#f3f4f6' },
  webContent: { maxWidth: 1100, width: '100%', alignSelf: 'center', flex: 1 },
  scrollFlex: { flex: 1 },
  screenLight: { backgroundColor: '#fafafa' },
  splash: { backgroundColor: '#111111', alignItems: 'center', justifyContent: 'center' },
  splashIconWrap: { marginBottom: 24, alignItems: 'center', justifyContent: 'center' },
  splashGlow: {
    position: 'absolute',
    width: 180,
    height: 180,
    backgroundColor: '#f97316',
    opacity: 0.2,
    borderRadius: 90,
  },
  splashTitle: { fontSize: 40, fontWeight: '800', color: '#ffffff', letterSpacing: -1 },
  splashAccent: { color: '#f97316' },
  splashSubtitle: { marginTop: 8, color: '#9ca3af', fontWeight: '700', letterSpacing: 2, fontSize: 12 },
  screenPad: { padding: 24, paddingBottom: 120 },
  headerBlock: { marginBottom: 24 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, alignItems: 'center' },
  ghostButton: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 12, backgroundColor: '#f3f4f6' },
  ghostButtonText: { fontSize: 12, fontWeight: '700', color: '#6b7280' },
  languageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: '#f3f4f6',
  },
  languageButtonText: { fontSize: 12, fontWeight: '700', color: '#6b7280' },
  languageBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  languageModalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 20,
  },
  languageModalTitle: { fontSize: 16, fontWeight: '800', color: '#111827', marginBottom: 12 },
  languageList: { gap: 8 },
  languageOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  languageOptionActive: { borderColor: '#f97316', backgroundColor: '#fff7ed' },
  languageOptionText: { fontSize: 14, fontWeight: '600', color: '#111827' },
  headerTitle: { fontSize: 28, fontWeight: '800', color: '#111827' },
  headerSubtitle: { marginTop: 8, color: '#6b7280', fontWeight: '600', fontSize: 16 },
  grid2: { flexDirection: 'row', gap: 12 },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    borderWidth: 1,
    borderColor: '#f3f4f6',
  },
  flexCard: { flex: 1 },
  label: { fontSize: 14, fontWeight: '700', color: '#6b7280' },
  input: { fontSize: 28, fontWeight: '800', color: '#111827', marginTop: 8 },
  validationText: { marginTop: 6, fontSize: 12, color: '#dc2626', fontWeight: '600' },
  goalRow: { flexDirection: 'row', marginTop: 12, gap: 10 },
  goalButton: { flex: 1, paddingVertical: 10, borderRadius: 16, borderWidth: 2 },
  goalButtonActive: { backgroundColor: '#f97316', borderColor: '#f97316' },
  goalButtonInactive: { borderColor: '#f3f4f6' },
  goalButtonText: { textAlign: 'center', fontWeight: '800', color: '#9ca3af', fontSize: 14 },
  goalButtonTextActive: { color: '#ffffff' },
  darkPanel: {
    backgroundColor: '#111111',
    padding: 24,
    borderRadius: 32,
    marginTop: 24,
  },
  darkPanelIcon: { position: 'absolute', right: 16, top: 12, opacity: 0.1 },
  labelRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  darkPanelLabelText: { color: '#f97316', fontWeight: '800', fontSize: 10, letterSpacing: 1 },
  darkPanelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
  },
  darkCaption: { color: '#9ca3af', fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  darkHero: { fontSize: 32, fontWeight: '800', color: '#ffffff', marginTop: 6 },
  darkHeroUnit: { fontSize: 12, fontWeight: '600', color: 'rgba(255,255,255,0.6)' },
  darkSmall: { fontSize: 18, fontWeight: '700', color: 'rgba(255,255,255,0.6)' },
  darkSmallUnit: { fontSize: 12, fontWeight: '600' },
  accountDangerZone: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 16,
  },
  accountDangerTitle: { fontSize: 13, fontWeight: '700', color: '#6b7280', marginBottom: 10 },
  accountDeleteButton: {
    borderWidth: 1,
    borderColor: '#fca5a5',
    backgroundColor: '#fef2f2',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
  },
  accountDeleteButtonDisabled: { opacity: 0.6 },
  accountDeleteButtonText: { color: '#dc2626', fontWeight: '800', fontSize: 13 },
  pfcRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 },
  pfcCell: { flex: 1, alignItems: 'center' },
  pfcLabelAccent: { color: '#f97316', fontSize: 10, fontWeight: '700' },
  pfcLabel: { color: '#9ca3af', fontSize: 10, fontWeight: '700' },
  pfcValue: { color: '#ffffff', fontSize: 18, fontWeight: '800', marginTop: 4 },
  sectionSpacer: { height: 12 },
  stepRow: { marginTop: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  stepText: { color: '#6b7280', fontWeight: '700', fontSize: 12 },
  stepDots: { flexDirection: 'row', gap: 6 },
  stepDot: { width: 10, height: 10, borderRadius: 999 },
  stepDotActive: { backgroundColor: '#111827' },
  stepDotInactive: { backgroundColor: '#e5e7eb' },
  primaryButton: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 24,
    backgroundColor: '#111827',
    paddingVertical: 16,
    borderRadius: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  primaryButtonDisabled: { opacity: 0.4 },
  stepButtonRow: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 24,
    flexDirection: 'row',
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: '#f3f4f6',
    paddingVertical: 16,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: { color: '#111827', fontWeight: '800' },
  primaryButtonCompact: {
    flex: 2,
    backgroundColor: '#111827',
    paddingVertical: 16,
    borderRadius: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  primaryButtonInline: {
    backgroundColor: '#f97316',
    paddingVertical: 16,
    borderRadius: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  primaryButtonText: { color: '#ffffff', fontWeight: '800' },
  dashboardPad: { padding: 24, paddingBottom: 120 },
  dashboardHeader: { marginBottom: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  dashboardActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  dashboardSectionSpacer: { marginTop: 8 },
  dashboardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  dashboardIcon: {
    width: 40,
    height: 40,
    backgroundColor: '#f97316',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardTitle: { fontSize: 22, fontWeight: '800', color: '#111827' },
  roundButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center' },
  actionCard: { flex: 1, borderRadius: 28, padding: 18, alignItems: 'center', justifyContent: 'center', gap: 10 },
  actionPrimary: { backgroundColor: '#f97316' },
  actionSecondary: { backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#f3f4f6' },
  actionIconWrap: { backgroundColor: 'rgba(255,255,255,0.2)', padding: 12, borderRadius: 20 },
  actionIconWrapSecondary: { backgroundColor: '#f3f4f6', padding: 12, borderRadius: 20 },
  actionText: { color: '#ffffff', fontWeight: '800', fontSize: 16, textAlign: 'center' },
  actionTextDark: { color: '#111827', fontWeight: '800', fontSize: 16, textAlign: 'center' },
  sectionTitleWrap: { marginBottom: 12 },
  sectionTitle: { fontSize: 20, fontWeight: '800', color: '#111827' },
  sectionSubtitle: { fontSize: 11, color: '#9ca3af', marginTop: 4, fontWeight: '600' },
  sectionLabel: { marginTop: 8, marginBottom: 4, fontSize: 12, fontWeight: '800', color: '#6b7280' },
  emptyCard: {
    borderWidth: 2,
    borderColor: '#f3f4f6',
    borderStyle: 'dashed',
    borderRadius: 28,
    padding: 32,
    alignItems: 'center',
  },
  emptyTitle: { color: '#9ca3af', fontWeight: '700' },
  emptyText: { marginTop: 6, color: '#d1d5db', fontSize: 12, textAlign: 'center' },
  cardStack: { gap: 12 },
  planRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  planRowCompact: { flexDirection: 'column', alignItems: 'stretch', gap: 10 },
  planSummaryButton: { flex: 1, flexDirection: 'row', alignItems: 'center', marginRight: 12, minWidth: 0 },
  planSummaryButtonCompact: { marginRight: 0, width: '100%' },
  planBaseImage: { width: 52, height: 52, borderRadius: 18, marginRight: 12 },
  planBaseImageCompact: { width: 48, height: 48, borderRadius: 16, marginRight: 10 },
  planInfo: { flex: 1, minWidth: 0 },
  planActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 8, flexWrap: 'wrap', flexShrink: 1 },
  planActionsCompact: { width: '100%', justifyContent: 'space-between', flexWrap: 'nowrap', gap: 6 },
  lightButton: {
    backgroundColor: '#f3f4f6',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  lightButtonCompact: { paddingVertical: 8, paddingHorizontal: 8, borderRadius: 12, minWidth: 36 },
  shopButton: {
    backgroundColor: '#fff7ed',
    borderWidth: 1,
    borderColor: '#fed7aa',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  shopButtonText: { color: '#f97316', fontWeight: '800', fontSize: 11 },
  shopButtonCompact: { paddingVertical: 8, paddingHorizontal: 8, borderRadius: 12, minWidth: 52, alignItems: 'center' },
  shopButtonTextCompact: { fontSize: 10 },
  planTagRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6, flexWrap: 'wrap' },
  planTagRowCompact: { gap: 6, marginBottom: 4 },
  planTag: { backgroundColor: '#ffedd5', color: '#c2410c', fontSize: 10, fontWeight: '800', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999, maxWidth: '100%' },
  planTagCompact: { fontSize: 9, paddingHorizontal: 8, paddingVertical: 3 },
  planDate: { color: '#d1d5db', fontSize: 10, fontWeight: '700', flexShrink: 1 },
  planDateCompact: { fontSize: 9 },
  planTitle: { fontSize: 18, fontWeight: '800', color: '#111827' },
  planTitleCompact: { fontSize: 14, lineHeight: 18 },
  darkButton: { backgroundColor: '#111827', paddingVertical: 10, paddingHorizontal: 16, borderRadius: 16 },
  darkButtonText: { color: '#ffffff', fontWeight: '800', fontSize: 12 },
  darkButtonCompact: { paddingVertical: 8, paddingHorizontal: 10, borderRadius: 12, minWidth: 78, alignItems: 'center' },
  darkButtonTextCompact: { fontSize: 11 },
  calendarButton: {
    marginTop: 12,
    alignSelf: 'flex-start',
    backgroundColor: '#111827',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 16,
  },
  calendarButtonText: { color: '#ffffff', fontWeight: '800', fontSize: 12 },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingVertical: 12,
    paddingHorizontal: 36,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  navItem: { alignItems: 'center', gap: 4 },
  navItemActive: { alignItems: 'center', gap: 4 },
  navLabel: { fontSize: 10, fontWeight: '800', color: '#d1d5db', textTransform: 'uppercase' },
  navLabelActive: { fontSize: 10, fontWeight: '800', color: '#f97316', textTransform: 'uppercase' },
  builderHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  squareButton: { width: 44, height: 44, borderRadius: 16, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center' },
  squareButtonLight: { width: 44, height: 44, borderRadius: 16, backgroundColor: '#ffffff', alignItems: 'center', justifyContent: 'center' },
  stepLabel: { fontSize: 10, color: '#d1d5db', fontWeight: '800', textTransform: 'uppercase' },
  builderTitle: { fontSize: 22, fontWeight: '800', color: '#111827' },
  progressTrack: { height: 6, backgroundColor: '#f3f4f6', borderRadius: 999, overflow: 'hidden', marginBottom: 24 },
  progressFill: { height: 6, backgroundColor: '#f97316' },
  sectionBlock: { marginBottom: 16 },
  choiceCard: { flex: 1, padding: 24, borderRadius: 28, borderWidth: 3, borderColor: '#f9fafb', alignItems: 'center' },
  choiceCardActive: { borderColor: '#f97316', backgroundColor: '#fff7ed' },
  choiceNumber: { fontSize: 36, fontWeight: '800', color: '#111827' },
  choiceUnit: { fontSize: 12, fontWeight: '800', color: '#9ca3af' },
  baseRow: { flexDirection: 'row', gap: 12, padding: 16, borderRadius: 24, borderWidth: 2, borderColor: '#f3f4f6', alignItems: 'center' },
  baseRowActive: { borderColor: '#f97316', backgroundColor: '#fff7ed' },
  autoRecommendedRow: { borderColor: '#fdba74', backgroundColor: '#fffaf0' },
  swapButton: {
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  swapButtonDisabled: { opacity: 0.5 },
  swapButtonText: { color: '#ffffff', fontSize: 11, fontWeight: '800' },
  baseIcon: { width: 56, height: 56, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f3f4f6', overflow: 'hidden' },
  baseImage: { width: 56, height: 56 },
  baseTitle: { fontSize: 16, fontWeight: '800', color: '#111827' },
  baseSubtitle: { fontSize: 11, color: '#9ca3af', marginTop: 4 },
  ingredientCard: { flex: 1, padding: 12, borderRadius: 20, borderWidth: 2, borderColor: '#f3f4f6' },
  ingredientCardActive: { borderColor: '#f97316', backgroundColor: '#fff7ed' },
  ingredientImage: { width: '100%', height: 120, borderRadius: 16, marginBottom: 8 },
  ingredientRowImage: { width: 70, height: 70, borderRadius: 16 },
  ingredientName: { fontSize: 14, fontWeight: '800', color: '#111827' },
  ingredientMeta: { fontSize: 10, color: '#9ca3af', marginTop: 4, fontWeight: '700' },
  checkBadge: { position: 'absolute', top: 8, right: 8, backgroundColor: '#f97316', padding: 6, borderRadius: 12 },
  fullButton: { marginTop: 16, backgroundColor: '#111827', paddingVertical: 16, borderRadius: 24, alignItems: 'center' },
  fullButtonDisabled: { opacity: 0.2 },
  fullButtonText: { color: '#ffffff', fontWeight: '800' },
  carbImage: { width: 70, height: 70, borderRadius: 16 },
  commitTitle: { fontSize: 26, fontWeight: '800', textAlign: 'center', color: '#111827', marginBottom: 12 },
  darkCard: { backgroundColor: '#111111', borderColor: 'transparent' },
  listRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.1)', paddingVertical: 10, gap: 12 },
  listRowCompact: { flexDirection: 'column', gap: 6 },
  listRowContent: { flex: 1, minWidth: 0 },
  listSectionLabel: { color: '#f97316', fontWeight: '800', fontSize: 12, marginTop: 12 },
  listLabel: { color: '#e5e7eb', fontWeight: '700', flexShrink: 1, lineHeight: 20 },
  listValue: { color: '#ffffff', fontWeight: '800', flexShrink: 0, maxWidth: '48%' },
  listValueCompact: { maxWidth: '100%' },
  listSecondaryMeta: { color: '#9ca3af', fontWeight: '600', fontSize: 11, lineHeight: 16, marginTop: 4 },
  listUnit: { color: '#6b7280', fontWeight: '600' },
  sideCard: { borderLeftWidth: 6, borderLeftColor: '#d1d5db' },
  sideCardAccent: { borderLeftWidth: 6, borderLeftColor: '#f97316' },
  sideCardTitle: { fontSize: 10, fontWeight: '800', color: '#9ca3af', textTransform: 'uppercase', marginBottom: 4 },
  sideCardNote: { fontSize: 11, color: '#6b7280', marginBottom: 10 },
  sideCardTitleAccent: { fontSize: 10, fontWeight: '800', color: '#f97316', textTransform: 'uppercase', marginBottom: 10 },
  pfcValueDark: { fontSize: 16, fontWeight: '800', color: '#111827' },
  pfcValueAccent: { fontSize: 16, fontWeight: '800', color: '#f97316' },
  linkButton: { alignItems: 'center', paddingVertical: 12 },
  linkButtonText: { color: '#9ca3af', fontWeight: '700' },
  pageTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 },
  pageTitle: { fontSize: 24, fontWeight: '800', color: '#111827' },
  pageTitleAccent: { color: '#f97316' },
  pageTitleSimple: { fontSize: 24, fontWeight: '800', color: '#111827' },
  bigCard: { padding: 0, overflow: 'hidden', borderColor: 'transparent' },
  bigImage: { width: '100%', height: 220 },
  bigCardBody: { padding: 16 },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  cardTitle: { fontSize: 20, fontWeight: '800', color: '#111827' },
  categoryTag: { fontSize: 10, fontWeight: '800', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999 },
  tagProtein: { backgroundColor: '#fee2e2', color: '#b91c1c' },
  tagVeg: { backgroundColor: '#dcfce7', color: '#15803d' },
  tagCarb: { backgroundColor: '#dbeafe', color: '#1d4ed8' },
  effectSectionWrap: {
    marginTop: 10,
    gap: 8,
    borderRadius: 14,
    padding: 12,
    backgroundColor: '#fff7ed',
    borderWidth: 1,
    borderColor: '#fed7aa',
  },
  effectRow: { gap: 2 },
  effectTitle: { fontSize: 11, fontWeight: '800', color: '#c2410c' },
  effectBody: { fontSize: 12, lineHeight: 18, fontWeight: '600', color: '#374151' },
  statGrid: { marginTop: 16, backgroundColor: '#f9fafb', borderRadius: 24, padding: 16, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  statCell: { width: '45%', alignItems: 'center' },
  statLabel: { fontSize: 10, fontWeight: '800', color: '#9ca3af', textTransform: 'uppercase' },
  statValue: { fontSize: 12, fontWeight: '800', color: '#111827', marginTop: 4 },
  emptyState: { alignItems: 'center', marginTop: 80, gap: 16 },
  emptyTitleLarge: { fontSize: 18, fontWeight: '800', color: '#111827', textAlign: 'center' },
  listCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', backgroundColor: '#ffffff', padding: 16, borderRadius: 24, borderWidth: 1, borderColor: '#f3f4f6', gap: 12 },
  listCardCompact: { flexDirection: 'column', gap: 8 },
  listCardContent: { flex: 1, minWidth: 0 },
  listCardTitle: { fontWeight: '800', color: '#111827', flexShrink: 1, lineHeight: 22 },
  listCardSubtext: { marginTop: 6, fontWeight: '700', color: '#9ca3af', fontSize: 12, lineHeight: 18 },
  listCardHint: { fontWeight: '800', color: '#9ca3af', fontSize: 12, flexShrink: 0, maxWidth: '42%' },
  listCardHintCompact: { maxWidth: '100%' },
  cookPad: { flex: 1, padding: 24 },
  cookCenter: { flex: 1 },
  cookContent: { gap: 16, paddingBottom: 24 },
  cookPhoto: { width: '100%', height: 220, borderRadius: 18 },
  cookIconWrap: { width: 130, height: 130, borderRadius: 40, alignItems: 'center', justifyContent: 'center', marginBottom: 20 },
  cookStepBadge: { position: 'absolute', bottom: -6, right: -6, backgroundColor: '#ffffff', width: 36, height: 36, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  cookStepBadgeText: { fontSize: 12, fontWeight: '800', color: '#111827' },
  cookTitle: { fontSize: 24, fontWeight: '800', color: '#111827', textAlign: 'center' },
  cookDesc: { marginTop: 12, color: '#9ca3af', fontWeight: '600', textAlign: 'center', paddingHorizontal: 16, fontSize: 16, lineHeight: 24 },
  tipCard: { marginTop: 24, width: '100%', backgroundColor: '#f9fafb', borderColor: 'transparent', paddingVertical: 20 },
  tipIcon: { position: 'absolute', top: 12, right: 12, opacity: 0.1 },
  tipLabelText: { fontSize: 12, fontWeight: '800', color: '#f97316', textTransform: 'uppercase', marginBottom: 8 },
  tipText: { color: '#6b7280', fontWeight: '700', fontSize: 14, lineHeight: 22 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(17,24,39,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  drawerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(17,24,39,0.5)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 24,
    gap: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  modalCardLarge: {
    maxWidth: 520,
    maxHeight: '80%',
  },
  calendarModalCard: {
    maxWidth: 560,
  },
  iconButton: {
    marginLeft: 'auto',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarNav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  calendarNavButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarMonthText: { fontSize: 14, fontWeight: '800', color: '#111827' },
  calendarWeekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    marginBottom: 6,
  },
  calendarWeekText: { width: '14.2857%', textAlign: 'center', fontSize: 10, fontWeight: '700', color: '#9ca3af' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  calendarCell: { width: '14.2857%', alignItems: 'center', marginBottom: 10 },
  calendarCellEmpty: { width: '14.2857%', height: 40 },
  calendarBadge: {
    width: 28,
    height: 28,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarBadgeText: { fontSize: 11, fontWeight: '800', color: '#0f172a' },
  calendarDayText: { marginTop: 4, fontSize: 10, fontWeight: '700', color: '#9ca3af' },
  drawerCard: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    gap: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: -6 },
  },
  calendarDetailList: { gap: 10, paddingBottom: 8 },
  calendarDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: '#f9fafb',
  },
  calendarDetailInfo: { flex: 1 },
  calendarDetailTitle: { fontSize: 14, fontWeight: '800', color: '#111827' },
  calendarDetailHint: { fontSize: 12, fontWeight: '700', color: '#6b7280', marginTop: 2 },
  modalTitle: { fontSize: 18, fontWeight: '800', color: '#111827' },
  modalTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  modalBody: { fontSize: 14, color: '#6b7280', fontWeight: '600', lineHeight: 20 },
  modalShopRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
  modalShopBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#fff7ed',
    borderWidth: 1,
    borderColor: '#fed7aa',
  },
  modalShopLabel: { fontSize: 13, fontWeight: '800', color: '#f97316' },
  floatingBackButton: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  modalImage: { width: '100%', height: 200, borderRadius: 16 },
  modalCheckRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 4 },
  modalCheckBox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
  },
  modalCheckBoxActive: { backgroundColor: '#f97316', borderColor: '#f97316' },
  modalCheckLabel: { fontSize: 13, fontWeight: '700', color: '#6b7280' },
  modalButton: {
    marginTop: 8,
    backgroundColor: '#f97316',
    borderRadius: 18,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalButtonText: { color: '#ffffff', fontWeight: '800', fontSize: 14 },
  authWrap: { flex: 1, padding: 24, justifyContent: 'center', gap: 12 },
  authTopRow: { alignItems: 'flex-end', marginBottom: 10 },
  authTitle: { fontSize: 28, fontWeight: '800', color: '#111827', textAlign: 'center' },
  authSubtitle: { textAlign: 'center', color: '#9ca3af', marginBottom: 12, fontWeight: '600' },
  authInput: { backgroundColor: '#f9fafb', borderRadius: 16, padding: 12, fontWeight: '600', color: '#111827' },
  authError: { color: '#dc2626', fontWeight: '700', textAlign: 'center' },
});
